name: Polybot Microservice Deployment

on:
  push:
    paths:
      - 'polybot/**'
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          cd polybot
          
          echo "${{ secrets.CERT_PEM }}" > cert.pem
          echo "${{ secrets.SSL_PRIVATE_KEY }}" > private.key
          
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

          IMAGE_NAME=polybot:${{ github.run_number }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME
          
          rm cert.pem private.key 

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2
      - name: Deploy new version
        run: |         
          # TODO your implementation here....     
     
