name: Yolo5 Microservice Deployment

on:
  push:
    paths:
      - 'yolo5/**'
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          cd yolo5
   
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

          IMAGE_NAME=yolo5:${{ github.run_number }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME          

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2
      - name: Deploy new version
        run: |         
          # TODO your implementation here....     
     
